<?php

namespace Wvision\Bundle\ImportDefinitionsBundle;

use Pimcore\Extension\Bundle\AbstractPimcoreBundle;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Wvision\Bundle\ImportDefinitionsBundle\DependencyInjection\Compiler\CleanerRegistryCompilerPass;
use Wvision\Bundle\ImportDefinitionsBundle\DependencyInjection\Compiler\FilterRegistryCompilerPass;
use Wvision\Bundle\ImportDefinitionsBundle\DependencyInjection\Compiler\InterpreterRegistryCompilerPass;
use Wvision\Bundle\ImportDefinitionsBundle\DependencyInjection\Compiler\ProviderRegistryCompilerPass;
use Wvision\Bundle\ImportDefinitionsBundle\DependencyInjection\Compiler\RunnerRegistryCompilerPass;
use Wvision\Bundle\ImportDefinitionsBundle\DependencyInjection\Compiler\SetterRegistryCompilerPass;

class ImportDefinitionsBundle extends AbstractPimcoreBundle
{
    /**
     * {@inheritdoc}
     */
    public function build(ContainerBuilder $builder)
    {
        parent::build($builder);

        $builder->addCompilerPass(new CleanerRegistryCompilerPass());
        $builder->addCompilerPass(new FilterRegistryCompilerPass());
        $builder->addCompilerPass(new InterpreterRegistryCompilerPass());
        $builder->addCompilerPass(new ProviderRegistryCompilerPass());
        $builder->addCompilerPass(new RunnerRegistryCompilerPass());
        $builder->addCompilerPass(new SetterRegistryCompilerPass());
    }

    public function getNiceName()
    {
        return 'Import Definitions';
    }

    public function getDescription()
    {
        return 'Import Definitions allows you to create reusable Definitions for Importing all kinds of files';
    }

    public function getVersion()
    {
        return '2.0.0';
    }

    public function getInstaller()
    {
        parent::getInstaller(); // TODO: Change the autogenerated stub
    }

    public function getJsPaths()
    {
        return [
            '/plugins/ImportDefinitions/static/js/startup.js',
            '/plugins/ImportDefinitions/static/js/definition/panel.js',
            '/plugins/ImportDefinitions/static/js/definition/item.js',
            '/plugins/ImportDefinitions/static/js/definition/configDialog.js',
            '/plugins/ImportDefinitions/static/js/provider/abstractprovider.js',
            '/plugins/ImportDefinitions/static/js/provider/csv.js',
            '/plugins/ImportDefinitions/static/js/provider/sql.js',
            '/plugins/ImportDefinitions/static/js/provider/json.js',
            '/plugins/ImportDefinitions/static/js/provider/xml.js',

            '/plugins/ImportDefinitions/static/js/interpreters/abstract.js',
            '/plugins/ImportDefinitions/static/js/interpreters/href.js',
            '/plugins/ImportDefinitions/static/js/interpreters/multihref.js',
            '/plugins/ImportDefinitions/static/js/interpreters/defaultvalue.js',
            '/plugins/ImportDefinitions/static/js/interpreters/asseturl.js',
            '/plugins/ImportDefinitions/static/js/interpreters/assetsurl.js',
            '/plugins/ImportDefinitions/static/js/interpreters/quantityvalue.js',

            '/plugins/ImportDefinitions/static/js/setters/abstract.js',
            '/plugins/ImportDefinitions/static/js/setters/fieldcollection.js',
            '/plugins/ImportDefinitions/static/js/setters/objectbrick.js',
            '/plugins/ImportDefinitions/static/js/setters/classificationstore.js',
            '/plugins/ImportDefinitions/static/js/setters/localizedfield.js'
        ];
    }

    public function getCssPaths()
    {
        return parent::getCssPaths(); // TODO: Change the autogenerated stub
    }
}
