services:
  Instride\Bundle\DataDefinitionsBundle\ElementsProcessManager\ImportListener:
    tags:
      - { name: 'kernel.event_listener', event: 'data_definitions.import.total', method: 'onTotalEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.import.progress', method: 'onProgressEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.import.status', method: 'onStatusEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.import.finished', method: 'onFinishedEvent' }
      - { name: 'kernel.event_listener', event: 'data_definitions.import.failure', method: 'onFailureEvent' }
